server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .html
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.10.6:3306/security?useSSL=false&allowMultiQueries=true
    username: root
    password: 1234
shiro:
  loginUrl: /security/login
  successUrl: /security/success
#配置mybatis的配置文件
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
